### ISSUE TITLE
Is Library 	 suitable to Big Json ?! 

### ISSUE THREAD

**Issue by emadph** [100rabhkr/GetJSON#3]
HI 
i hava big Json (24 MG) 
Now i want to know is Library support such huge Data ?!

**Comment by 100rabhkr** [comment]
I haven't tried it with such huge data. Let me try

**Comment by 100rabhkr** [comment]
In theory it should

**Comment by 100rabhkr** [comment]
Update: it won't. Try my other library [DownZ](https://github.com/100rabhkr/DownZLibrary)
